[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "git-recall"
version = "1.0.0"
description = "A local AI-powered Git commit assistant with semantic memory."
dependencies = [
    "requests",
    "chromadb"
]

[project.scripts]
git-recall = "ai_commit.main:main"

[tool.setuptools.packages.find]
include = ["ai_commit"]